# fly.toml app configuration file generated for long-feather-4033 on 2023-11-06T14:17:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-feather-4033"
primary_region = "lax"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[env]
  PHX_HOST = "long-feather-4033.fly.dev"
  PORT = "8080"

[mounts]
  source = "data"
  destination = "/data"
  processes= ["app"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
